// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIeCek-v9LCNuRSftVIbL36NuSx2dlbg',
    appId: '1:561025241791:web:3f402e1d4b6b735e6f2c0a',
    messagingSenderId: '561025241791',
    projectId: 'myfirebaseapp-6f58d',
    authDomain: 'myfirebaseapp-6f58d.firebaseapp.com',
    storageBucket: 'myfirebaseapp-6f58d.firebasestorage.app',
    measurementId: 'G-VGSSHV9YCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt98dHbDZoCZqEPlTWPlIEmRd1YF8fxLs',
    appId: '1:561025241791:android:68d0d1416873a9376f2c0a',
    messagingSenderId: '561025241791',
    projectId: 'myfirebaseapp-6f58d',
    storageBucket: 'myfirebaseapp-6f58d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACg7kH68Y9mZfEUEhnS5GfVK3Jf9JZvOk',
    appId: '1:561025241791:ios:3dc917ff72d175826f2c0a',
    messagingSenderId: '561025241791',
    projectId: 'myfirebaseapp-6f58d',
    storageBucket: 'myfirebaseapp-6f58d.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACg7kH68Y9mZfEUEhnS5GfVK3Jf9JZvOk',
    appId: '1:561025241791:ios:3dc917ff72d175826f2c0a',
    messagingSenderId: '561025241791',
    projectId: 'myfirebaseapp-6f58d',
    storageBucket: 'myfirebaseapp-6f58d.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxIeCek-v9LCNuRSftVIbL36NuSx2dlbg',
    appId: '1:561025241791:web:76160330b1a2fec06f2c0a',
    messagingSenderId: '561025241791',
    projectId: 'myfirebaseapp-6f58d',
    authDomain: 'myfirebaseapp-6f58d.firebaseapp.com',
    storageBucket: 'myfirebaseapp-6f58d.firebasestorage.app',
    measurementId: 'G-P507D97GDV',
  );
}
